---
- name: Preparing Workstation
  hosts: localhost
  connection: local
  tasks:

    - name: Installing Linux Apps
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
      loop:
          - vim
          - htop
          - wget
          - python3-pip
          - make
          - git
          - flameshot
          - mlocate
          - cherrytree

    - block:
      - name: Install Virtualbox Oracle Key
        become: true
        apt_key:
          url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'
          state: present
      - name: Add Virtualbox Oracle repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian bionic contrib'
          state: present
          filename: virtualbox
      - name: Install Oracle Virtualbox
        become: true
        apt:
          name: virtualbox-6.1

    - block:
      - name: Installing Vagrant 2.2.15
        become: true
        unarchive:
          src: 'https://releases.hashicorp.com/vagrant/2.2.15/vagrant_2.2.15_linux_amd64.zip'
          dest: /usr/local/bin
          remote_src: yes

          
    - block:
      - name: Install Microsoft Key
        become: true
        apt_key:
          url: 'https://packages.microsoft.com/keys/microsoft.asc'
          state: present
      - name: Add Microsoft Teams Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main'
          state: present
          filename: teams
      - name: Install Microsoft Teams
        become: true
        apt:
          name: teams
        

    - block: 
      - name: Install Brave Key
        become: true
        apt_key:
          url: 'https://brave-browser-apt-release.s3.brave.com/brave-core.asc'
          state: present
      - name: Install Brave Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main'
          state: present
          filename: brave
      - name: Install Brave Browser
        become: true
        apt:
          name: brave-browser
